import React, { useState } from 'react';
import { 
  ShieldAlert, 
  Search, 
  ChevronRight, 
  Tag, 
  FilePlus,
  CheckCircle
} from 'lucide-react';
import { useBitcoin } from '../../context/BitcoinContext';
import { BitcoinRiskLead, BitcoinTransaction } from '../../types/bitcoin';

interface Props {
  onSelectTx: (tx: BitcoinTransaction) => void;
  onCreateCase: (lead: BitcoinRiskLead) => void;
}

const BitcoinRiskQueue: React.FC<Props> = ({ onSelectTx, onCreateCase }) => {
  const { riskQueue, transactions } = useBitcoin();
  const [filterSeverity, setFilterSeverity] = useState('ALL');
  const [searchTerm, setSearchTerm] = useState('');

  const filteredLeads = riskQueue.filter(lead => {
    const matchesSearch = 
      lead.lead_id.toLowerCase().includes(searchTerm.toLowerCase()) ||
      lead.entity_id.toLowerCase().includes(searchTerm.toLowerCase()) ||
      lead.txid.toLowerCase().includes(searchTerm.toLowerCase()) ||
      lead.explanation.toLowerCase().includes(searchTerm.toLowerCase());

    if (filterSeverity === 'ALL') return matchesSearch;
    return matchesSearch && lead.risk_level === filterSeverity;
  });

  return (
    <div className="space-y-4">
      {/* Risk Queue Header */}
      <div className="bg-[#0b1324]/90 rounded-2xl p-4 border border-[#172442] shadow-lg flex flex-col md:flex-row justify-between items-center gap-4">
        <div>
          <h2 className="text-base font-bold text-white flex items-center gap-2">
            <ShieldAlert className="w-5 h-5 text-red-500" />
            Prioritized Investigative Lead Queue
          </h2>
          <p className="text-xs text-gray-400">Ranked anomalous leads generated by V.E.C.T.O.R multi-model intelligence engine</p>
        </div>

        <div className="flex items-center gap-3 w-full md:w-auto">
          <div className="relative flex-1 md:w-64">
            <Search className="w-4 h-4 text-gray-400 absolute left-3 top-2.5" />
            <input
              type="text"
              placeholder="Search leads, entity, explanation..."
              value={searchTerm}
              onChange={e => setSearchTerm(e.target.value)}
              className="w-full bg-[#0e172a] border border-[#1e2e50] focus:border-amber-500/60 rounded-xl pl-9 pr-3 py-1.5 text-xs text-gray-200 placeholder-gray-500 outline-none"
            />
          </div>

          <select
            value={filterSeverity}
            onChange={e => setFilterSeverity(e.target.value)}
            className="text-xs bg-[#0e172a] border border-[#1e2e50] text-gray-300 rounded-xl px-3 py-1.5 outline-none focus:border-amber-500"
          >
            <option value="ALL">All Severities</option>
            <option value="CRITICAL">Critical Priority</option>
            <option value="HIGH">High Priority</option>
            <option value="MEDIUM">Medium Priority</option>
            <option value="LOW">Low Priority</option>
          </select>
        </div>
      </div>

      {/* Leads List */}
      <div className="space-y-3">
        {filteredLeads.length === 0 ? (
          <div className="bg-[#0b1324]/90 rounded-2xl p-12 text-center border border-[#172442] shadow-lg">
            <CheckCircle className="w-12 h-12 text-emerald-400 mx-auto mb-3" />
            <h3 className="text-base font-bold text-white">Queue is Clear</h3>
            <p className="text-xs text-gray-400 mt-1">No active leads match your current severity filters.</p>
          </div>
        ) : (
          filteredLeads.map(lead => {
            const relatedTx = transactions.find(t => t.txid === lead.txid);
            const isCrit = lead.risk_level === 'CRITICAL';
            const isHigh = lead.risk_level === 'HIGH';
            const isMed = lead.risk_level === 'MEDIUM';

            return (
              <div 
                key={lead.lead_id} 
                className="bg-[#0b1324]/90 rounded-2xl p-5 border border-[#172442] shadow-lg hover:border-amber-500/40 transition-all space-y-3"
              >
                <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-2">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className={`px-2.5 py-1 rounded-md text-xs font-bold ${
                      isCrit ? 'bg-red-500/20 text-red-400 border border-red-500/40' :
                      isHigh ? 'bg-orange-500/20 text-orange-400 border border-orange-500/40' :
                      isMed ? 'bg-amber-500/20 text-amber-400 border border-amber-500/40' :
                      'bg-emerald-500/20 text-emerald-400 border border-emerald-500/40'
                    }`}>
                      {lead.risk_level} • SCORE {lead.risk_score}
                    </span>
                    <span className="font-mono text-xs font-bold text-gray-200">{lead.lead_id}</span>
                    <span className="text-xs text-gray-600">•</span>
                    <span className="font-mono text-xs text-indigo-300 bg-indigo-500/15 border border-indigo-500/30 px-2 py-0.5 rounded font-medium">
                      {lead.entity_id}
                    </span>
                  </div>

                  <div className="flex items-center gap-2">
                    {relatedTx && (
                      <button
                        onClick={() => onSelectTx(relatedTx)}
                        className="inline-flex items-center text-xs font-semibold text-cyan-400 bg-cyan-500/10 hover:bg-cyan-500/20 border border-cyan-500/30 px-3 py-1.5 rounded-lg transition-colors"
                      >
                        Inspect TX <ChevronRight className="w-3.5 h-3.5 ml-0.5" />
                      </button>
                    )}
                    <button
                      onClick={() => onCreateCase(lead)}
                      className="inline-flex items-center text-xs font-semibold text-gray-900 bg-amber-400 hover:bg-amber-300 px-3 py-1.5 rounded-lg transition-colors font-bold shadow-sm"
                    >
                      <FilePlus className="w-3.5 h-3.5 mr-1 text-gray-900" /> Open Dossier
                    </button>
                  </div>
                </div>

                {/* Explanation Strip */}
                <p className="text-xs text-gray-300 leading-relaxed bg-[#0e172a] p-3 rounded-xl border border-[#1b2b4d]">
                  {lead.explanation}
                </p>

                {/* Pattern Tags */}
                <div className="flex flex-wrap items-center gap-1.5 pt-1">
                  <span className="text-[11px] font-semibold text-gray-400 mr-1">Signals:</span>
                  {lead.signals?.map((sig, i) => (
                    <span key={i} className="inline-flex items-center text-[10px] px-2 py-0.5 rounded bg-amber-500/10 text-amber-300 border border-amber-500/20 font-medium">
                      <Tag className="w-2.5 h-2.5 mr-1 text-amber-400" />
                      {sig.replace(/_/g, ' ')}
                    </span>
                  ))}
                  <span className="text-[10px] text-gray-400 ml-auto font-mono">
                    TXID: {lead.txid?.slice(0, 16)}...
                  </span>
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
};

export default BitcoinRiskQueue;
